config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :traffic_tickets
  resources :cars
  resources :owners

  resources :departments, only: [] do
    resources :cities, only: [:index]
  end

  resources :automakers, only: [:index, :show, :new, :edit, :create, :update] do
    resources :model_cars
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/traffic_ticket.rb
#
# Tabla traffic_tickets
#
# id                    :integer PK
# owner_id              :integer FK
# car_id                :integer FK
# traffic_officer_id    :integer FK
# traffic_infraction_id :integer FK
# city_id               :integer FK
# date                  :date
# address               :string
# cost                  :decimal(15,2)
# created_at:           :datetime
# update_at:            :datetime

class TrafficTicket < ApplicationRecord
  belongs_to :owner
  belongs_to :car, optional: true
  belongs_to :traffic_officer
  belongs_to :traffic_infraction
  belongs_to :city

  validates :owner_id, :traffic_officer_id, :traffic_infraction_id, :city_id, presence: true

  SEARCH_ATTRIBUTES = ['owners.name', 'owners.last_name', "owners.name || ' ' || owners.last_name", :address, "cities.name", 'cars.registration', "substring(registration from 0 for 4)", "substring(registration from 5)", "substring(registration from 0 for 4) || substring(registration from 5)", 'traffic_infractions.article', 'traffic_officers.name']
  SEARCH_JOINS      = [:owner, :car, :traffic_infraction, :traffic_officer, :city]
  DEFAULT_INCLUDES  = [:owner, :car, :traffic_infraction, :traffic_officer, {city: [:department]}]

  include Search

  def full_address
    "#{self.city.try(:department).try(:name)}, #{self.city.try(:name)}, #{self.address}"
  end

  def self.to_select filter = {}
    self.where(filter).pluck(:id, :id)
  end
end

app/controllers/traffic_tickets_controller.rb
class TrafficTicketsController < ApplicationController
  before_action :set_traffic_ticket, only: [:show, :edit, :update, :destroy]

  # GET /traffic_tickets
  # GET /traffic_tickets.json
  def index
    @traffic_tickets = TrafficTicket.search(search_params[:text], search_params[:sort], search_params[:sort_type])
  end

  # GET /traffic_tickets/1
  # GET /traffic_tickets/1.json
  def show
  end

  # GET /traffic_tickets/new
  def new
    @traffic_ticket = TrafficTicket.new
  end

  # GET /traffic_tickets/1/edit
  def edit
  end

  # POST /traffic_tickets
  # POST /traffic_tickets.json
  def create
    @traffic_ticket = TrafficTicket.new(traffic_ticket_params)

    respond_to do |format|
      if @traffic_ticket.save
        format.html { redirect_to @traffic_ticket, notice: 'Traffic ticket was successfully created.' }
        format.json { render :show, locals: {message: 'Multa creada.'}, status: :created, location: @traffic_ticket }
      else
        format.html { render :new }
        format.json { render json: {errors: @traffic_ticket.errors}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traffic_tickets/1
  # PATCH/PUT /traffic_tickets/1.json
  def update
    respond_to do |format|
      if @traffic_ticket.update(traffic_ticket_params)
        format.html { redirect_to @traffic_ticket, notice: 'Traffic ticket was successfully updated.' }
        format.json { render :show, locals: {message: 'Multa Actualizada.'}, status: :ok, location: @traffic_ticket }
      else
        format.html { render :edit }
        format.json { render json: {errors: @traffic_ticket.errors}, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffic_tickets/1
  # DELETE /traffic_tickets/1.json
  def destroy
    @traffic_ticket.destroy
    respond_to do |format|
      format.html { redirect_to traffic_tickets_url, notice: 'Traffic ticket was successfully destroyed.' }
      format.json { render json: {message: 'Multa Eliminada.'} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traffic_ticket
      @traffic_ticket = TrafficTicket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traffic_ticket_params
      params.require(:traffic_ticket).permit(:owner_id, :car_id, :traffic_officer_id, :traffic_infraction_id, :city_id, :date, :address, :cost)
    end
end

app/helpers/traffic_tickets_helper.rb
module TrafficTicketsHelper
  def ticket_table_class(ticket)
    ticket.owner.active? ? '' : 'danger'
  end
end

app/views/traffic_tickets/_edit.json.haml
%h1 Editar multa

= render 'form'

= link_to 'Mostrar', traffic_ticket_path(@traffic_ticket, format: :json), remote: true
\|
= link_to 'Atras', root_path(format: :json, anchor: 'traffic_tickets'), remote: true

app/views/traffic_tickets/_form.json.haml
= form_for @traffic_ticket, format: params[:format], remote: true do |f|
  - if @traffic_ticket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@traffic_ticket.errors.count, "error")} prohibited this traffic_ticket from being saved:"
      %ul
        - @traffic_ticket.errors.full_messages.each do |msg|
          %li= msg

  .row
    .field.col-md-6
      = f.label 'Usuario Infractor', required: true
      = f.select :owner_id, Owner.to_select, {include_blank: 'Seleccione Infractor'}, required: true, class: "form-control"
      = link_to 'Crear Usuario', new_owner_path(format: :json), remote: true, data: {container: "#mainModal", title: 'Nuevo Usuario', select: '#traffic_ticket_owner_id'}
    .field.col-md-6
      = f.label 'Vehiculo de la infraccion'
      = f.select :car_id, Car.to_select, {include_blank: 'Seleccione Vehiculo'}, class: "form-control"
      = link_to 'Crear Vehiculo', new_car_path(format: :json), remote: true, data: {container: "#mainModal", title: 'Nuevo Vehiculo', select: '#traffic_ticket_car_id'}
  .row
    .field.col-md-6
      = f.label 'Agente de transito', required: true
      = f.select :traffic_officer_id, TrafficOfficer.to_select, {include_blank: 'Seleccione Agente'}, class: "form-control", required: true
      -#= link_to 'Crear Agente de Transito', new_traffic_officer_path(format: :json), remote: true, data: {container: "#mainModal", title: 'Nuevo Agente', select: '#traffic_ticket_traffic_officer_id'}
    .field.col-md-6
      = f.label 'Infraccion', required: true
      = f.select :traffic_infraction_id, TrafficInfraction.to_select, {include_blank: 'Seleccione Infraccion'}, class: "form-control infraction-select", required: true
      -#= link_to 'Crear Infraccion', new_traffic_infraction_path(format: :json), remote: true, data: {container: "#mainModal", title: 'Nueva Infraccion', select: '#traffic_ticket_traffic_infraction_id'}
  .row
    .field.col-md-6
      = f.label 'Departamento/Estado', required: true
      = select_tag :department_id, options_for_select(Department.pluck(:name, :id), f.object.city.try(:department_id)), include_blank: 'Seleccione departamento de la infraccion', class: "form-control department_select", required: true, data: {city_select: '#traffic_ticket_city_id'}
    .field.col-md-6
      = f.label 'Ciudad'
      = f.select :city_id, City.where(department_id: f.object.city.try(:department_id)).pluck(:name, :id), {include_blank: 'Primero seleccione departamento'}, class: "form-control", required: true
  .row
    .field.col-md-6
      = f.label 'Direccion'
      = f.text_field :address, class: "form-control", required: true, placeholder: 'Carrera # Calle #'
    .field.col-md-6
      = f.label 'Fecha Infraccion'
      = f.text_field :date, data: {provide: 'datepicker'}, required: true, readonly: true, class: "form-control", placeholder: 'dd/mm/yyyy', value: f.object.date.try(:strftime, '%d/%m/%Y')
  .row
    .field.col-md-6
      = f.label 'Tipo'
      .row
        .col-md-6
          = radio_button_tag 'tipo', 'urban', f.object.traffic_infraction.try(:cost_urban_area) == f.object.cost ,data: {price: f.object.traffic_infraction.try(:cost_urban_area)}
          = f.label 'Urbano', for: 'tipo_urban'
        .col-md-6
          = radio_button_tag 'tipo', 'rural', f.object.traffic_infraction.try(:cost_rural_area) == f.object.cost, data: {price: f.object.traffic_infraction.try(:cost_rural_area)}
          = f.label 'Rural', for: 'tipo_rural'
    .field.col-md-6
      = f.label "Precio"
      .row
        .col-md-2.text-right
          $ COP
        .col-md-10
          = f.text_field :cost, placeholder: '', type: 'number', required: true, min: '0.1', step: '0.01', class: "form-control", readonly: true
  .actions.col-md-6.pull-right
    = f.submit 'Guardar', class: 'btn pull-right btn btn-primary'

app/views/traffic_tickets/_list.json.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Propietario
      %th Automovil
      %th Agente de transito
      %th Infraccion
      %th Direccion
      %th Fecha
      %th Precio
      %th{colspan: 3}

  %tbody
    - @traffic_tickets.each do |traffic_ticket|
      %tr{class: ticket_table_class(traffic_ticket)}
        %td= traffic_ticket.owner.full_name
        %td= traffic_ticket.car.try(:registration)
        %td= traffic_ticket.traffic_officer.name
        %td= traffic_ticket.traffic_infraction.article
        %td= traffic_ticket.full_address
        %td= traffic_ticket.date
        %td= number_to_currency traffic_ticket.cost, precision: 0, unit: 'COP $'
        %td= link_to 'Mostrar', traffic_ticket_path(traffic_ticket, format: :json), remote: true
        %td= link_to 'Editar', edit_traffic_ticket_path(traffic_ticket, format: :json), remote: true unless traffic_ticket.owner.archived?
        %td= link_to 'Eliminar', traffic_ticket_path(traffic_ticket, format: :json), remote: true, method: :delete, remote: true, class: 'deleted', :data => { :confirm => 'Esta seguro?' }

- unless @traffic_tickets.present?
  %h4 Sin resultados
%br

app/views/traffic_tickets/_new.json.haml
.navigation
  %h1 Nueva Multa

= render 'form'
.navigation
  = link_to 'Atras', root_path(format: :json, anchor: 'traffic_tickets'), remote: true

app/views/traffic_tickets/_search.html.haml
.row
  .col-md-8.col-md-offset-2
    = form_for :search, url: traffic_tickets_path(format: :json), method: 'get', remote: true, html: {data: {container: '#traffic_tickets_results'}, class: 'auto-submit'} do |f|
      .row
        .col-md-3
          = f.text_field :text, placeholder: 'Busqueda', class: 'form-control'
        .col-md-3
          = f.select :sort, [['Nombre', 'owners.name'], ['Precio', 'cost'], ['Ciudad', 'cities.name'], ["Fecha", "traffic_tickets.date"]], {include_blank: 'Ordenar por'}, class: "form-control"
        .col-md-3
          = f.select :sort_type, [['Ascendente','asc'], ['Descendente', 'desc']], {}, class: "form-control"
        .col-md-3
          = f.submit 'Buscar', class: 'btn btn-info form-control'

#traffic_tickets_results

app/views/traffic_tickets/_show.json.haml
%p
  %b Infractor:
  = @traffic_ticket.owner
%p
  %b Automovil:
  = @traffic_ticket.car
%p
  %b Agente de transito:
  = @traffic_ticket.traffic_officer
%p
  %b Infraccion:
  = @traffic_ticket.traffic_infraction
%p
  %b Direccion:
  = "#{@traffic_ticket.city.to_s}, #{@traffic_ticket.address}"
%p
  %b Date:
  = @traffic_ticket.date
%p
  %b Cost:
  = @traffic_ticket.cost

= link_to 'Editar', edit_traffic_ticket_path(@traffic_ticket, format: :json), remote: true
\|
= link_to 'Atras', root_path(format: :json, anchor: 'traffic_tickets'), remote: true