config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :traffic_tickets
  resources :cars
  resources :owners

  resources :departments, only: [] do
    resources :cities, only: [:index]
  end

  resources :automakers, only: [:index, :show, :new, :edit, :create, :update] do
    resources :model_cars
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/automaker.rb
#
# Tabla automakers
#
# id          :integer PK
# name        :string
# address     :string
# created_at: :datetime
# update_at:  :datetime

class Automaker < ApplicationRecord
  validates :name, presence: true

  has_many :model_cars

  SEARCH_ATTRIBUTES = [:name, :address]
  SEARCH_JOINS = []
  DEFAULT_INCLUDES = []

  include Search

  def to_s
    name
  end

  def self.to_select filter = {}
    self.where(filter).pluck(:name, :id)
  end
end

app/controllers/automakers_controller.rb
class AutomakersController < ApplicationController
  before_action :set_automaker, only: [:show, :edit, :update]

  # GET /automakers
  # GET /automakers.json
  def index
    @automakers = Automaker.search(search_params[:text], search_params[:sort], search_params[:sort_type])
  end

  # GET /automakers/1
  # GET /automakers/1.json
  def show
  end

  # GET /automakers/new
  def new
    @automaker = Automaker.new
  end

  # GET /automakers/1/edit
  def edit
  end

  # POST /automakers
  # POST /automakers.json
  def create
    @automaker = Automaker.new(automaker_params)

    respond_to do |format|
      if @automaker.save
        format.html { redirect_to @automaker, notice: 'Automaker was successfully created.' }
        format.json { render :show, locals: {message: 'Fabricante creado.'}, status: :created, location: @automaker }
      else
        format.html { render :new }
        format.json { render json: @automaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automakers/1
  # PATCH/PUT /automakers/1.json
  def update
    respond_to do |format|
      if @automaker.update(automaker_params)
        format.html { redirect_to @automaker, notice: 'Automaker was successfully updated.' }
        format.json { render :show, locals: {message: 'Fabricante Actualizado.'}, status: :ok, location: @automaker }
      else
        format.html { render :edit }
        format.json { render json: @automaker.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automaker
      @automaker = Automaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def automaker_params
      params.require(:automaker).permit(:name, :address)
    end
end

app/views/automakers/_edit.json.haml
%h1 Editar Fabricante
= render 'form', automaker: @automaker
= link_to 'Mostrar', automaker_path(@automaker, format: :json), remote: true
|
= link_to 'Atras', root_path(format: :json, anchor: 'automakers'), remote: true

app/views/automakers/_form.json.haml
= form_for @automaker , format: params[:format], remote: true do |f|
  - if @automaker.errors.any?
    #error_explanation
      %h2
        = pluralize(@automaker.errors.count, "error")
        prohibited this automaker from being saved:
      %ul
        - @automaker.errors.full_messages.each do |message|
          %li= message
  .row
    .field.col-md-6
      = f.label 'Nombre', required: true
      = f.text_field :name, required: true, class: "form-control"
    .field.col-md-6
      = f.label 'Direccion', required: true
      = f.text_field :address, required: true, class: "form-control"
  .row
    .actions.col-md-6.pull-right
      = f.submit 'Guardar', class: 'btn pull-right btn btn-primary'

app/views/automakers/_list.json.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Nombre
      %th Direccion
      %th{:colspan => "2"}

  %tbody
    - @automakers.each do |automaker|
      %tr
        %td= automaker.name
        %td= automaker.address
        %td= link_to 'Mostrar', automaker_path(automaker, format: :json), remote: true
        %td= link_to 'Editar', edit_automaker_path(automaker, format: :json), remote: true

- unless @automakers.present?
  %h4 Sin resultados
%br/

app/views/automakers/_new.json.haml
.navigation
  %h1 Nuevo Frabricante
= render 'form'
.navigation
  = link_to 'Atras', root_path(format: :json, anchor: 'automakers'), remote: true

app/views/automakers/_search.html.haml
.row
  .col-md-8.col-md-offset-2
    = form_for :search, url: automakers_path(format: :json), method: 'get', remote: true, html: {data: {container: '#automakers_results'}, class: 'auto-submit'} do |f|
      .row
        .col-md-3
          = f.text_field :text, placeholder: 'Busqueda', class: 'form-control'
        .col-md-3
          = f.select :sort, [['Nombre', 'automakers.name'], ['Direccion', 'address']], {include_blank: 'Ordenar por'}, class: "form-control"
        .col-md-3
          = f.select :sort_type, [['Ascendente','asc'], ['Descendente', 'desc']], {}, class: "form-control"
        .col-md-3
          = f.submit 'Buscar', class: 'btn btn-info form-control'

#automakers_results

app/views/automakers/_show.json.haml
%p
  %strong Nombre:
  = @automaker.name
%p
  %strong Direccion:
  = @automaker.address
.panel-group#accordion{role: 'tablist', aria_multiselectable: 'true'}
  .panel.panel-default
    .panel-heading{role: 'tab', id: 'headingModelCars'}
      %h4.panel-title
        %a{role:'button', href: '#model_cars', data: {toggle: 'collapse', parent: '#accordion'}, aria: {expanded: 'true', controls: 'model_cars'}}
          Modelos
  #model_cars.panel-collapse.collapse.in{role: 'tabpanel', aria_labelledby: 'headingModelCars'}
    = render partial: '/model_cars/search', formats: [:html], locals: {automaker: @automaker}
    = link_to 'Crear modelo', new_automaker_model_car_path(@automaker, format: :json), remote: true, class: 'btn btn-primary pull-right'

= link_to 'Editar', edit_automaker_path(@automaker, format: :json), remote: true
|
= link_to 'Atras', root_path(format: :json, anchor: 'automakers'), remote: true