config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :traffic_tickets
  resources :cars
  resources :owners

  resources :departments, only: [] do
    resources :cities, only: [:index]
  end

  resources :automakers, only: [:index, :show, :new, :edit, :create, :update] do
    resources :model_cars
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/_index.html.haml
.panel-group#accordion{role: 'tablist', aria_multiselectable: 'true'}
  .panel.panel-default

    .panel-heading{role: 'tab', id: 'headingTrafficTickets'}
      %h4.panel-title
        %a{role:'button', href: '#traffic_tickets', data: {toggle: 'collapse', parent: '#accordion'}, aria: {expanded: 'true', controls: 'traffic_tickets'}}
          Multas de Transito
    #traffic_tickets.panel-collapse.collapse.in{role: 'tabpanel', aria_labelledby: 'headingTrafficTickets'}
      = render partial: '/traffic_tickets/search'
      = link_to 'Crear multa', new_traffic_ticket_path(format: :json), remote: true, class: 'btn btn-primary pull-right'

    .panel-heading{role: 'tab', id: 'headingOwners'}
      %h4.panel-title
        %a{role:'button', href: '#owners', data: {toggle: 'collapse', parent: '#accordion'}, aria: {expanded: 'true', controls: 'owners'}}
          Usuarios

    #owners.panel-collapse.collapse{role: 'tabpanel', aria_labelledby: 'headingOwners'}
      = render partial: '/owners/search'
      = link_to 'Crear usuario', new_owner_path(format: :json), remote: true, class: 'btn btn-primary pull-right'

    .panel-heading{role: 'tab', id: 'headingAutomakers'}
      %h4.panel-title
        %a{role:'button', href: '#automakers', data: {toggle: 'collapse', parent: '#accordion'}, aria: {expanded: 'true', controls: 'automakers'}}
          Fabricantes de autos

    #automakers.panel-collapse.collapse{role: 'tabpanel', aria_labelledby: 'headingAutomakers'}
      = render partial: '/automakers/search'
      = link_to 'Crear Fabricantes', new_automaker_path(format: :json), remote: true, class: 'btn btn-primary pull-right'

    .panel-heading{role: 'tab', id: 'headingCars'}
      %h4.panel-title
        %a{role:'button', href: '#cars', data: {toggle: 'collapse', parent: '#accordion'}, aria: {expanded: 'true', controls: 'cars'}}
          Automoviles

    #cars.panel-collapse.collapse{role: 'tabpanel', aria_labelledby: 'headingCars'}
      = render partial: '/cars/search'
      = link_to 'Crear Automovil', new_car_path(format: :json), remote: true, class: 'btn btn-primary pull-right'

app/views/home/index.html.haml
= render partial: 'home/index'