config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :traffic_tickets
  resources :cars
  resources :owners

  resources :departments, only: [] do
    resources :cities, only: [:index]
  end

  resources :automakers, only: [:index, :show, :new, :edit, :create, :update] do
    resources :model_cars
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
#
# Tabla cars
#
# id                :integer PK
# registration      :string
# registration_date :date
# model_car         :integer FK
# owner             :integer FK
# created_at:       :datetime
# update_at:        :datetime

class Car < ApplicationRecord
  REGISTRATION_REGEX = /^(\w{3})(\W|\_)*(\w{2,})\s*$/

  belongs_to :model_car
  belongs_to :owner

  before_save :parameterize_registration if :registration_changed?

  SEARCH_ATTRIBUTES = [:registration, "substring(registration from 0 for 4)", "substring(registration from 5)", "substring(registration from 0 for 4) || substring(registration from 5)", 'model_cars.name', "to_char(model_cars.year, '9999')", 'owners.last_name', 'owners.name', 'owners.nit', 'automakers.name']
  SEARCH_JOINS = [:owner, model_car: [:automaker]]
  DEFAULT_INCLUDES = [:owner, {model_car: [:automaker]}]

  include LogicalDestroy
  include Search

  validates :model_car, :owner, :registration, :registration_date, presence: true
  def to_s
    registration
  end

  def self.to_select filter = {}
    self.active.where(filter).pluck(:registration, :id)
  end

  def parameterize_registration
    if self.registration =~ REGISTRATION_REGEX
      self.registration.gsub!(REGISTRATION_REGEX, '\1-\3')
    end

    self.registration = self.registration.upcase
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.search(search_params[:text], search_params[:sort], search_params[:sort_type], custom_filter_params)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, locals: {message: 'Automovil creado.'}, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, locals: {message: 'Automovil Actualizado.'}, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { render json: {message: 'Automovil Eliminado.'} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:registration, :registration_date, :model_car_id, :owner_id)
    end

    def custom_filter_params
      {
        owner_id: search_params[:owner_id]
      }.delete_if { |k,v| v.blank? }
    end
end

app/views/cars/_edit.json.haml
%h1 Editar automovil

= render 'form'

= link_to 'Mostrar', car_path(@car, format: :json), remote: true
\|
= link_to 'Atras', root_path(format: :json, anchor: 'cars'), remote: true

app/views/cars/_form.json.haml
= form_for @car, format: params[:format], remote: true do |f|
  - if @car.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |msg|
          %li= msg

  .row
    .field.col-md-6
      = f.label 'Matricula', required: true
      = f.text_field :registration, required: true, class: "form-control"
    .field.col-md-6
      = f.label 'Fecha de registro', required: true
      = f.text_field :registration_date, data: {provide: 'datepicker'}, required: true, readonly: true, class: "form-control", placeholder: 'dd/mm/yyyy'
  .row
    .field.col-md-6
      = f.label 'Fabricante', required: true
      = select_tag :automaker_id, options_for_select(Automaker.to_select, f.object.model_car.try(:automaker_id)), include_blank: 'Seleccione Fabricante', class: "form-control fabricante_select", required: true, data: {model_select: '#car_model_car_id'}
      = link_to 'Crear Fabricante', new_automaker_path(format: :json), remote: true, data: {container: "#mainModal", step: '2', select: '#automaker_id'}
    .field.col-md-6
      = f.label 'Modelo', required: true
      = f.select :model_car_id, ModelCar.to_select(automaker_id: f.object.model_car.try(:automaker_id)), {include_blank: 'Seleccione primero un Fabricante'}, required: true, class: "form-control"
      = link_to 'Crear Modelo', '', remote: true, id: 'create_model_car', data: {container: "#mainModal", step: '2', select: '#car_model_car_id'}
  .row
    .field.col-md-6
      = f.label 'Propietario', required: true
      = f.select :owner_id, Owner.to_select, {include_blank: 'Seleccione Propietario'}, required: true, class: "form-control"
      = link_to 'Crear Usuario', new_owner_path(format: :json), remote: true, data: {container: "#mainModal", step: '2', select: '#car_owner_id'}

  .row
    .actions.col-md-6.pull-right
      = f.submit 'Guardar', class: 'btn pull-right btn btn-primary'

app/views/cars/_list.json.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Matricula
      %th Fecha Matricula
      %th Frabricante/Modelo
      %th Propietario
      %th{:colspan => "3"}

  %tbody
    - @cars.each do |car|
      %tr
        %td= car.registration
        %td= car.registration_date
        %td= car.model_car.full_name
        %td= car.owner.full_name
        %td= link_to 'Mostrar', car_path(car, format: :json), remote: true
        %td= link_to 'Editar', edit_car_path(car, format: :json), remote: true
        %td= link_to 'Eliminar', car_path(car, format: :json), remote: true, :method => :delete, :data => { :confirm => 'Esta seguro?' }, class: 'deleted'
- unless @cars.present?
  %h4 Sin resultados
%br

app/views/cars/_new.json.haml
.navigation
  %h1 Nuevo automovil
= render 'form'
.navigation
  = link_to 'Atras', root_path(format: :json, anchor: 'cars'), remote: true

app/views/cars/_search.html.haml
.row
  .col-md-10.col-md-offset-1
    = form_for :search, url: cars_path(format: :json), method: 'get', remote: true, html: {data: {container: '#cars_results'}, class: 'auto-submit'} do |f|
      .row
        .col-md-2
          = f.text_field :text, placeholder: 'Busqueda', class: 'form-control'
        .col-md-3
          = f.select :owner_id, Owner.all_to_select, {include_blank: 'Propietario'}, class: "form-control"
        .col-md-3
          = f.select :sort, [['Matricula', 'cars.registration'], ['Fecha de registro', 'cars.registration_date'], ["Modelo", "model_cars.year"]], {include_blank: 'Ordenar por'}, class: "form-control"
        .col-md-2
          = f.select :sort_type, [['Ascendente','asc'], ['Descendente', 'desc']], {}, class: "form-control"
        .col-md-2
          = f.submit 'Buscar', class: 'btn btn-info form-control'

#cars_results

app/views/cars/_show.json.haml
%p
  %b Matricula:
  = @car.registration
%p
  %b Fecha Matricula:
  = @car.registration_date
%p
  %b Frabricante/Modelo:
  = @car.model_car.full_name
%p
  %b Propietario:
  = @car.owner.full_name

= link_to 'Editar', edit_car_path(@car, format: :json), remote: true
\|
= link_to 'Atras', root_path(format: :json, anchor: 'cars'), remote: true